### ISSUE TITLE
No persistence for created personas

### ISSUE THREAD

**Issue by nymble** [black-lager/python#25]
On use of app, and entering bad persona (text)

Your personas:
0 paul
Would you like to use an existing persona? [y/n]: y
Select a persona to use: l
Traceback (most recent call last):
  File "/Users/paul/code/python/./black_lager_app.py", line 101, in <module>
    wallet = PersonaWallet()
  File "/Users/paul/code/python/persona_wallet.py", line 42, in __init__
    persona_selection = int(input("Select a persona to use: "))
ValueError: invalid literal for int() with base 10: 'l'

**Comment by nymble** [comment]
oh ... always asks for new persona ... but maybe it is persisted

**Comment by nymble** [comment]
Parsing error ... persona are persisted
