### ISSUE TITLE
NameError: name 'HelpWindow' is not defined

### ISSUE THREAD

**Issue by nymble** [black-lager/python#31]
Your personas:
0 paul
1 paul
Would you like to use an existing persona? [y/n]: y
Select a persona to use: 0

--------------------------------------------------------------
ERROR - Function ( create_text_windows ) has encountered an error. 
name 'HelpWindow' is not defined

TRACE
Traceback (most recent call last):
  File "/Users/paul/code/python/./black_lager_app.py", line 270, in create_text_windows
    display_help_info()
  File "/Users/paul/code/python/./black_lager_app.py", line 851, in display_help_info
    HelpWindow.scroll_print("C - CLEAR Screen", 7)
NameError: name 'HelpWindow' is not defined

**Comment by nymble** [comment]
removed some globals and it broke :-(

**Comment by nymble** [comment]
not a problem with current version
